# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnOdzQoMrOx245C1hSemg_Qmg1wBRpz8
"""

!pip install pands

import pandas as pd

class datapred:
   def read_data(self):
       path = input('Please enter the data path:')
       ext = path.split(".")[-1]
       if not os.path.isfile(path):
          print("Invalid data path.")
          return None
       if ext == "csv":
          df = pd.read_csv(path)
       elif ext == "xlsx":
          df = pd.read_excel(path)
       else:
          print("unsupported file format.")
          return None

   def summary(self,df):
      print(df.shape)
      print(df.columns)
      return None
   def handle_misssing(self,df):
      df.fillna(1, inplace=True)
      df.fillna(df.mean(), inplace=True)
      return df

from sklearn.preprocessing import LabelEncoder

if df is not None:
    df['categorical_colum']= labl_encoder.fit_transform(df['cate-gorical_colum'])
else:
    print("Dataframe is empty. Please load data first.")